### ISSUE TITLE
make document-store error: pymongo.errors.InvalidURI

### ISSUE THREAD

**Issue by ido777** [the-full-stack/ask-fsdl#57]
I tried to install it with no luck.
I progressed a bit and found some errors I the guide.
I will open a PR for the errors I already overcome, but now I am stuck on 

> make document-store 

ExecutionError: Could not deserialize remote exception due to local error:
No module named 'pymongo'
This can happen if your local environment does not have the remote exception definitions.
Here is the remote traceback:
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/app.py", line 176, in drop_docs
    docstore.drop(collection, db)
  File "/pkg/docstore.py", line 17, in drop
    collection = get_collection(collection, db, client)
  File "/pkg/docstore.py", line 44, in get_collection
    db = get_database(db, client)
  File "/pkg/docstore.py", line 59, in get_database
    client = client or connect()
  File "/pkg/docstore.py", line 81, in connect
    client = pymongo.MongoClient(connection_string, connect=True, appname="ask-fsdl")
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 639, in __init__
    res = uri_parser.parse_uri(
  File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 461, in parse_uri
    raise InvalidURI('Bad database name "%s"' % dbase)
pymongo.errors.InvalidURI: Bad database name "/<my_user>:<password>@fsdl"

**Comment by charlesfrye** [comment]
Hmm, I haven't been able to reproduce this exact error. It is triggered when the connection string contains [certain characters](https://github.com/mongodb/mongo-python-driver/blob/f3e323a866bd64171bc9b8c2f3c798f719f34dcf/pymongo/uri_parser.py#L370). Some combination of them triggers that parsing failure, rather than the friendlier error [here](https://github.com/mongodb/mongo-python-driver/blob/3f687f71fb1f6c6e7fbf742cc7731213f3521627/pymongo/uri_parser.py#L70-L74).

If you didn't expect for your MongoDB username or password to have those characters, then there's a bug elsewhere. I haven't been testing this in different shells.

Meanwhile, I've added url quoting to the connection string construction, so if you did expect it, the connection should work.

**Comment by charlesfrye** [comment]
believed closed by 773d2f0, reopen if not!

**Comment by ido777** [comment]
Nothing changed

**Comment by charlesfrye** [comment]
word, if you would be comfortable sharing the connection info for the database you're using over Discord DM, then i can test this behavior more effectively

**Comment by ido777** [comment]
1) I am  comfortable sharing the connection info for the database you're
using over Discord DM
BUT
2) I found my mistake (learned what is modal on the way)
SO
3) I will open 2 clean PR, one to avoid others do the same mistake, and the
other to debug Mongo connection (and to use python instead of sh).
